/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package pl.online_courses_mail.online_courses_mail.event;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class UserAndMailDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -4414070834786320268L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserAndMailDTO\",\"namespace\":\"pl.online_courses_mail.online_courses_mail.event\",\"fields\":[{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"mail\",\"type\":\"string\"}],\"version\":\"1\"}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<UserAndMailDTO> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<UserAndMailDTO> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<UserAndMailDTO> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<UserAndMailDTO> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<UserAndMailDTO> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this UserAndMailDTO to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a UserAndMailDTO from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a UserAndMailDTO instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static UserAndMailDTO fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.CharSequence username;
    private java.lang.CharSequence mail;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public UserAndMailDTO() {
    }

    /**
     * All-args constructor.
     *
     * @param username The new value for username
     * @param mail     The new value for mail
     */
    public UserAndMailDTO(java.lang.CharSequence username, java.lang.CharSequence mail) {
        this.username = username;
        this.mail = mail;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return username;
            case 1:
                return mail;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                username = (java.lang.CharSequence) value$;
                break;
            case 1:
                mail = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'username' field.
     *
     * @return The value of the 'username' field.
     */
    public CharSequence getUsername() {
        return username;
    }


    /**
     * Sets the value of the 'username' field.
     *
     * @param value the value to set.
     */
    public void setUsername(java.lang.CharSequence value) {
        this.username = value;
    }

    /**
     * Gets the value of the 'mail' field.
     *
     * @return The value of the 'mail' field.
     */
    public CharSequence getMail() {
        return mail;
    }


    /**
     * Sets the value of the 'mail' field.
     *
     * @param value the value to set.
     */
    public void setMail(java.lang.CharSequence value) {
        this.mail = value;
    }

    /**
     * Creates a new UserAndMailDTO RecordBuilder.
     *
     * @return A new UserAndMailDTO RecordBuilder
     */
    public static pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder newBuilder() {
        return new pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder();
    }

    /**
     * Creates a new UserAndMailDTO RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new UserAndMailDTO RecordBuilder
     */
    public static pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder newBuilder(pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder other) {
        if (other == null) {
            return new pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder();
        } else {
            return new pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder(other);
        }
    }

    /**
     * Creates a new UserAndMailDTO RecordBuilder by copying an existing UserAndMailDTO instance.
     *
     * @param other The existing instance to copy.
     * @return A new UserAndMailDTO RecordBuilder
     */
    public static pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder newBuilder(pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO other) {
        if (other == null) {
            return new pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder();
        } else {
            return new pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder(other);
        }
    }

    /**
     * RecordBuilder for UserAndMailDTO instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserAndMailDTO>
            implements org.apache.avro.data.RecordBuilder<UserAndMailDTO> {

        private java.lang.CharSequence username;
        private java.lang.CharSequence mail;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.username)) {
                this.username = data().deepCopy(fields()[0].schema(), other.username);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.mail)) {
                this.mail = data().deepCopy(fields()[1].schema(), other.mail);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing UserAndMailDTO instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.username)) {
                this.username = data().deepCopy(fields()[0].schema(), other.username);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.mail)) {
                this.mail = data().deepCopy(fields()[1].schema(), other.mail);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'username' field.
         *
         * @return The value.
         */
        public java.lang.CharSequence getUsername() {
            return username;
        }


        /**
         * Sets the value of the 'username' field.
         *
         * @param value The value of 'username'.
         * @return This builder.
         */
        public pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder setUsername(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.username = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'username' field has been set.
         *
         * @return True if the 'username' field has been set, false otherwise.
         */
        public boolean hasUsername() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'username' field.
         *
         * @return This builder.
         */
        public pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder clearUsername() {
            username = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'mail' field.
         *
         * @return The value.
         */
        public java.lang.CharSequence getMail() {
            return mail;
        }


        /**
         * Sets the value of the 'mail' field.
         *
         * @param value The value of 'mail'.
         * @return This builder.
         */
        public pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder setMail(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.mail = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'mail' field has been set.
         *
         * @return True if the 'mail' field has been set, false otherwise.
         */
        public boolean hasMail() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'mail' field.
         *
         * @return This builder.
         */
        public pl.online_courses_mail.online_courses_mail.event.UserAndMailDTO.Builder clearMail() {
            mail = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public UserAndMailDTO build() {
            try {
                UserAndMailDTO record = new UserAndMailDTO();
                record.username = fieldSetFlags()[0] ? this.username : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.mail = fieldSetFlags()[1] ? this.mail : (java.lang.CharSequence) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<UserAndMailDTO>
            WRITER$ = (org.apache.avro.io.DatumWriter<UserAndMailDTO>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<UserAndMailDTO>
            READER$ = (org.apache.avro.io.DatumReader<UserAndMailDTO>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeString(this.username);

        out.writeString(this.mail);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.username = in.readString(this.username instanceof Utf8 ? (Utf8) this.username : null);

            this.mail = in.readString(this.mail instanceof Utf8 ? (Utf8) this.mail : null);

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.username = in.readString(this.username instanceof Utf8 ? (Utf8) this.username : null);
                        break;

                    case 1:
                        this.mail = in.readString(this.mail instanceof Utf8 ? (Utf8) this.mail : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










